// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCQqweocuzrqmvoOg1AgD_ApPz-4oOSiA',
    appId: '1:240290986230:web:fd41050e477713cc5794d7',
    messagingSenderId: '240290986230',
    projectId: 'finora-app-66138',
    authDomain: 'finora-app-66138.firebaseapp.com',
    storageBucket: 'finora-app-66138.firebasestorage.app',
    measurementId: 'G-CVJK8ES37B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4pE1X4PF1BbpVJS58-pww3i46CmGWF1Y',
    appId: '1:240290986230:android:dc5bd898225167555794d7',
    messagingSenderId: '240290986230',
    projectId: 'finora-app-66138',
    storageBucket: 'finora-app-66138.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLqJGlbtEMVpCd3N0lsoHLoVTg02Dphs',
    appId: '1:240290986230:ios:aab2399ccb2c72405794d7',
    messagingSenderId: '240290986230',
    projectId: 'finora-app-66138',
    storageBucket: 'finora-app-66138.firebasestorage.app',
    iosBundleId: 'com.example.smartBudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuLqJGlbtEMVpCd3N0lsoHLoVTg02Dphs',
    appId: '1:240290986230:ios:aab2399ccb2c72405794d7',
    messagingSenderId: '240290986230',
    projectId: 'finora-app-66138',
    storageBucket: 'finora-app-66138.firebasestorage.app',
    iosBundleId: 'com.example.smartBudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCQqweocuzrqmvoOg1AgD_ApPz-4oOSiA',
    appId: '1:240290986230:web:0e10294484bdcf455794d7',
    messagingSenderId: '240290986230',
    projectId: 'finora-app-66138',
    authDomain: 'finora-app-66138.firebaseapp.com',
    storageBucket: 'finora-app-66138.firebasestorage.app',
    measurementId: 'G-7MYW6R64FK',
  );
}
